# This yaml file automatically sets up the DB on the host machine

---

# Where we're installing the files
- hosts: db_host
  gather_facts: yes # Collects info and returns it to you after playbook is run
  become: true # sudo

  # Setup the db by syncing the folder with all relevant files
  tasks:

  - name: Sync environment folder
    synchronize:
      src: /home/ubuntu/environment
      dest: /home/ubuntu/
  
  - name: Download mongod 3.2 key 
    shell: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv D68FA50FEA312927

  - name: Download the version from the net
    shell: echo "deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

  - name: Update sources list
    command: apt-get update -y

  - name: Install 3.2 mongod
    shell: sudo apt-get install -y mongodb-org=3.2.20 mongodb-org-server=3.2.20 mongodb-org-shell=3.2.20 mongodb-org-mongos=3.2.20 mongodb-org-tools=3.2.20
    ignore_errors: yes

  - name: Remove the mongod.conf file
    file:
      path: /etc/mongod.conf
      state: absent
  
  - name: Link my config file
    shell: ln -s /home/ubuntu/environment/db/mongod.conf /etc/mongod.conf

  - name: Restart mongod service
    service: 
      name: mongod 
      state: restarted
  
  - name: Start mongod
    service: 
      name: mongod 
      state: started 
      enabled: yes
    become: true