# This yaml file automatically sets up the DB on the host machine

---

# Where we're installing the files
- hosts: db_host_test
  become: true # sudo
  handlers:
    - name: Restart mongod
      service:
        name: mongod
        state: restarted
        enabled: true

  # Setup the db by syncing the folder with all relevant files
  tasks:
  - name: Sync environment folder
    synchronize:
      src: /home/ubuntu/environment
      dest: /home/ubuntu/
  
  - name: Update Packges
    apt: update_cache=yes
  
  - name: Add mongod Apt key
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-3.2.asc
      state: present
  
  - name: Create a .list file 
    copy:
      dest: "/etc/apt/sources.list.d/mongodb-org-3.2.list"
      content: |
        deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse

  - name: Update sources list
    command: apt-get update -y
  
  - name: Install mongodb with all relevant packages
    apt:
      pkg: mongodb-org=3.2.20
      state: present

  - name: Remove the mongod.conf file
    file:
      path: /etc/mongod.conf
      state: absent
  
  - name: Link my config file
    file:
      src: /home/ubuntu/environment/db/mongod.conf
      dest: /etc/mongod.conf
      state: link
    notify: Restart mongod

  - name: Enable and Start mongod
    systemd: 
      name: mongod 
      state: started 
      enabled: yes
    